### ISSUE TITLE
Change release filename to use non-URI special delimiter

### ISSUE THREAD

**Issue by nate998877** [Metallis/Metal-Marker-Myriad#2]
You cannot navigate to your release file directly since the `.` delimiter is converted to `_`. Resulting in a required 302 redirect to download the pack & causing issues see https://github.com/BoyC/GW2TacO/pull/134.

**Comment by Metallis** [comment]
I design my packs primarily for Blish HUD, which doesn't suffer this issue. I'll consider changing for future releases, but it might cause more trouble than it solves.
