### ISSUE TITLE
Wiki link not working

### ISSUE THREAD

**Issue by mriot** [Metallis/Metal-Marker-Myriad#3]
Hi o/

the wiki link seems not to be working.

On the README it says: 
"For a full list of features, hop on over to the [Wiki](https://github.com/Metallis/Metal-Marker-Myriad/wiki)!"

**Comment by Metallis** [comment]
Wiki hadn't been created yet because I've been lazy. Here's the list you're looking for! https://github.com/Metallis/Metal-Marker-Myriad/wiki/Pack-contents
