### ISSUE TITLE
Cannot disable the Toxic Krait Historian trail

### ISSUE THREAD

**Issue by Rase24** [Metallis/Metal-Marker-Myriad#5]
I'm just interested in the EoD/SotO markers, so I disabled the rest. However there's still some trails on Sparkly Fen and Timberline Falls for example that I'm unable to disable. Using TaCO, not sure if Blish has the same issue.

**Comment by Metallis** [comment]
Hi Rase, is it those two maps specifically? There are trails for 7 different maps for that particular category.

**Comment by Metallis** [comment]
Issue isolated and fixed, Will be updated with the new version, hopefully tomorrow. I'd mis-categorized the trails and icons, relative to the defined category structure.
